# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Build-Instagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Build-Instagram
  pod 'Appirater'

  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Storage'

  target 'Build-InstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Build-InstagramUITests' do
    # Pods for testing
  end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
  end
 end
end

end
