# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Build-Instagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Build-Instagram

  target 'Build-InstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Build-InstagramUITests' do
    # Pods for testing
  end

end
